using OpportunityOS.Domain.Enums;

namespace OpportunityOS.Domain.Entities;

/// <summary>
/// Human-reviewable outreach draft generated by the AI Copilot layer.
/// Always created as <see cref="GeneratedMessageStatus.Draft"/>; never sent automatically.
/// </summary>
public sealed class GeneratedMessage
{
    public Guid Id { get; private set; }
    public Guid JobPostingId { get; private set; }
    public Guid OpportunityMatchId { get; private set; }
    /// <summary>The profile this draft was tailored for (the same job yields a different draft per profile).</summary>
    public Guid CandidateProfileId { get; private set; }
    public string LinkedInMessage { get; private set; } = string.Empty;
    public string CoverLetter { get; private set; } = string.Empty;
    public string EmailSubject { get; private set; } = string.Empty;
    public string EmailBody { get; private set; } = string.Empty;
    public string CvTailoringNotes { get; private set; } = string.Empty;
    public string FollowUpMessage { get; private set; } = string.Empty;
    public string HumanReviewNotes { get; private set; } = string.Empty;
    public GeneratedMessageStatus Status { get; private set; }

    // Audit (spec §"AI Copilot Layer"): every AI output is traceable.
    public string PromptVersion { get; private set; } = string.Empty;
    public string ModelName { get; private set; } = string.Empty;
    public DateTime CreatedAtUtc { get; private set; }

    private GeneratedMessage() { }

    public GeneratedMessage(
        Guid jobPostingId,
        Guid opportunityMatchId,
        string linkedInMessage,
        string coverLetter,
        string emailSubject,
        string emailBody,
        string cvTailoringNotes,
        string followUpMessage,
        string humanReviewNotes,
        string promptVersion,
        string modelName,
        Guid candidateProfileId = default)
    {
        Id = Guid.NewGuid();
        JobPostingId = jobPostingId;
        OpportunityMatchId = opportunityMatchId;
        CandidateProfileId = candidateProfileId;
        LinkedInMessage = linkedInMessage;
        CoverLetter = coverLetter;
        EmailSubject = emailSubject;
        EmailBody = emailBody;
        CvTailoringNotes = cvTailoringNotes;
        FollowUpMessage = followUpMessage;
        HumanReviewNotes = humanReviewNotes;
        PromptVersion = promptVersion;
        ModelName = modelName;
        Status = GeneratedMessageStatus.Draft;
        CreatedAtUtc = DateTime.UtcNow;
    }

    public void SetStatus(GeneratedMessageStatus status) => Status = status;
}
